//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseCategory_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseCategory_Table()
        {
            this.ProductCategory_Table = new HashSet<ProductCategory_Table>();
        }
    
        public int BaseCatId { get; set; }
        public string BaseCatName { get; set; }
        public string BaseCatDesc { get; set; }
        public System.DateTime BaseCatCreateDate { get; set; }
        public string BaseCatCreatedBy { get; set; }
        public string BaseCatUpdatedBy { get; set; }
        public System.DateTime BaseCatUpdateDate { get; set; }
        public int BaseCatIsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory_Table> ProductCategory_Table { get; set; }
    }
}
