//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory_Table()
        {
            this.Product_Table = new HashSet<Product_Table>();
        }
    
        public int ProductCatId { get; set; }
        public int BaseCatid { get; set; }
        public string ProductCatName { get; set; }
        public System.DateTime ProductCatCreatedDate { get; set; }
        public string ProductCatCreatedBy { get; set; }
        public string ProductCateUpdatedBy { get; set; }
        public System.DateTime ProductCatUpdatedDate { get; set; }
        public int ProductCatIsDeleted { get; set; }
    
        public virtual BaseCategory_Table BaseCategory_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Table> Product_Table { get; set; }
    }
}
