//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Table
    {
        public int ServiceId { get; set; }
        public int Productid { get; set; }
        public int Locationid { get; set; }
        public string ServiceName { get; set; }
        public decimal DeliveryCharge { get; set; }
        public string ServiceDesc { get; set; }
        public string ServiceCreatedBy { get; set; }
        public System.DateTime ServiceCreatedDate { get; set; }
        public string ServiceUpdatedBy { get; set; }
        public System.DateTime ServiceUpdatedDate { get; set; }
        public int ServiceIsDeleted { get; set; }
    
        public virtual Location_Table Location_Table { get; set; }
        public virtual Product_Table Product_Table { get; set; }
    }
}
